### ISSUE TITLE
No module named 'cutadapt'

### ISSUE THREAD

**Issue by annamalkova8** [GuyTeichman/RNAlysis#11]
**Describe the bug**
when im trying to install fastq or GUI I get the error: No module named 'cutadapt'

**Screenshots**
<img width="737" alt="image" src="https://user-images.githubusercontent.com/107634244/221786369-b8ac7afa-d352-41f5-9851-186acb04519b.png">

**Desktop (please complete the following information):**
MacOs

**Comment by GuyTeichman** [comment]
Hi,
Thanks for reporting this bug. The issue should be resolved in the next release.
In the meantime - you can resolve the issue by installing cutadapt.
You can either do that via pip:
`pip install cutadapt`
Or by installing the fastq module:
`pip install RNAlysis[fastq]`
Or by installing the full version of RNAlysis:
`pip install RNAlysis[all]`

Please let me know if any of those options resolved your issue.

Best,
Guy.
