### ISSUE TITLE
RNAlysis.dmg not found

### ISSUE THREAD

**Issue by dlijavetzky** [GuyTeichman/RNAlysis#13]
Hi, I just downloaded the file 'RNAlysis-3.5.2_macos.zip'. After unzipping I get a file named 'RNAlysis', but not the expected 'RNAlysis.dmg' file

Could you help me?

**Comment by GuyTeichman** [comment]
Hi,
the stand-alone app for MacOS contains a single file called 'RNAlysis.app', not a dmg file. 
You can follow this guide to open the file and run RNAlysis:
https://support.apple.com/en-il/guide/mac-help/mh40616/mac

Please let me know if that works for you. 

Best,
Guy.

**Comment by dlijavetzky** [comment]
Hi Guy,

Thanks for the info. The unzipped file didn't have the ‘.app’ extension, but I just added the extension and it worked.

Best,

Diego
