### ISSUE TITLE
Unable to run RNAlysis 

### ISSUE THREAD

**Issue by Rajeshwarira** [GuyTeichman/RNAlysis#15]
Unable to run RNAlysis
     I tried to run RNAlysis with the data given in the example part of user guide(analysis 1) as a sample run since I'm using this for first time. I was not able run it and getting the following errror which I attached as photo. Please do help me troubleshooting this.
Device version: Windows 10
![IMG20230406160416](https://user-images.githubusercontent.com/128403613/230705611-2aa45a2a-3f43-45bf-b50e-27db8f2a6307.jpg)

**Comment by GuyTeichman** [comment]
Hi Rajeshwarira, 
It looks like the file you're trying to open is a Microsoft Excel file (.xlsx), and not a csv file, and this is the source of the issue.

I would suggest that you open the file with a program like Excel, and then click on "File" - >"Save As", and change the format through the "Save As Type" drop-down menu to "CSV (Comma Delimited)".

See the link below for more details:
https://www.google.com/url?sa=t&source=web&rct=j&url=https://support.microsoft.com/en-us/office/import-or-export-text-txt-or-csv-files-5250ac4c-663c-47ce-937b-339e391393ba%23:~:text%3DYou%2520can%2520convert%2520an%2520Excel,or%2520CSV%2520(Comma%2520delimited).&ved=2ahUKEwi6oq_3qNv7AhULi_0HHduqCr8QFnoECA0QBQ&usg=AOvVaw0eUOr90h9lvor4Q0b0nw0n

Feel free post another comment here if you're still having trouble loading the file.
Good luck with your analysis!

**Comment by Rajeshwarira** [comment]
Thank you so much😊. I'll try it and let you know how it goes.

**Comment by Rajeshwarira** [comment]
Thank you for the response it worked well. I need help in installing kallisto.
I tried to add path using command prompt and the following appeared.
Please do tell me how should I install and run kallisto.

**Comment by Rajeshwarira** [comment]
Thank you for the response it worked well. I need help in installing kallisto.
I tried to add path using command prompt and the following appeared.
Please do tell me how should I install and run kallisto.
![Uploading IMG20230413122259.jpg…]()

**Comment by Rajeshwarira** [comment]
Thank you for the response it worked well. I need help in installing kallisto.
I tried to add path using command prompt and the following appeared.
Please do tell me how should I install and run kallisto.
![IMG20230413122259](https://user-images.githubusercontent.com/128403613/231680633-31772d31-35e5-4c86-9ae4-4d584e7fd1c2.jpg)

**Comment by GuyTeichman** [comment]
Hi,
did you download and unzip kallisto from their website?

**Comment by Rajeshwarira** [comment]
Yes, I did.

**Comment by Rajeshwarira** [comment]
Okay I'll try and let you know ☺️ thank you for your support.

**Comment by Rajeshwarira** [comment]
It worked ☺️Thank you so much for your support.
