### ISSUE TITLE
GO Enrichment Analysis mouse ensembl ids mapping problem: AssertionError: Dataset 'PR' is not a valid Uniprot Dataset to map gene names/IDs from.

### ISSUE THREAD

**Issue by clockgene** [GuyTeichman/RNAlysis#16]
**Describe the bug**
latest RNAlysis 3.7.0,  same bug on 3.6.2.
When trying to run Enrichment Analysis using Gene Ontology (GO) dataset, with my enrichment set (400 ENSMUSG Ensembl gene ids) and background set (13700 ids) of Mus musculus genes, I get this error:

Traceback (most recent call last):
  File "rnalysis\gui\gui.py", line 3733, in finish_enrichment
  File "rnalysis\gui\gui_widgets.py", line 329, in run
  File "rnalysis\enrichment.py", line 637, in go_enrichment
  File "rnalysis\utils\enrichment_runner.py", line 157, in run
  File "rnalysis\utils\enrichment_runner.py", line 1061, in fetch_annotations
  File "rnalysis\utils\enrichment_runner.py", line 1071, in _generate_annotation_df
  File "rnalysis\utils\enrichment_runner.py", line 1129, in _translate_gene_ids
  File "rnalysis\utils\io.py", line 1058, in map_gene_ids
  File "rnalysis\utils\validation.py", line 178, in validate_uniprot_dataset_name
AssertionError: Dataset 'PR' is not a valid Uniprot Dataset to map gene names/IDs from. Valid Uniprot Datasets are: UniProtKB AC/ID, UniProtKB AC, UniProtKB ID, UniProtKB_to, .... # I have shortened the list.

Sometimes: Dataset 'RefSeq' is not valid Uniprot Dataset....

KEGG dataset works fine.

**To Reproduce**
1. Go to 'Enrichment Analysis' and load datasets, choose External dataset GO, choose organism (Mus) and gene_id_type (Ensembl), rest default.
2. Click on 'run'
3. See error

**Expected behavior**
KEGG dataset works fine, but not GO dataset.

**Screenshots**
see traceback copy

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Version 22H2

**How did you install RNAlysis?**
 - Stand-alone app

**Comment by GuyTeichman** [comment]
Hi clockgene, 
Thank you for reporting this issue!

When you run GO enrichment analysis, RNAlysis attempts so automatically map the gene IDs of the GO annotations to whichever gene ID type you are using. That works well most of the time, but sometimes it can't find a good match and it discards some of the annotations (these are the warnings you observed). 

It looks like there is a specific database called 'PR' that is not supported by the UniProtKB gene ID mapping service, leading to the error. 

In the next release of RNAlysis (in a few weeks) you should not run into this error anymore. 
However, in the meantime, you can add "PR" to your excluded databases in the enrichment analysis, using a parameter called 'excluded_databases'. That way, RNAlysis won't fetch PR annotations at all, and you won't run into this error. 

Alternatively, you can use the parameter 'databases' to limit your search of annotations to specific databases. 

Please let me know if that worked for you, and feel free to write again about any other issues or concerns. 

Best of luck with your analysis, 
Guy.

**Comment by clockgene** [comment]
Dear Guy, I have actually tried adding 'PR' to excluded dbs, but it did not work and either returned 'PR' again or 'RefSeq'. I have just tried it again today, but unfortunately I get another error at the start of the run:

requests.exceptions.HTTPError: 400 Client Error: undefined field text for url: http://golr-aux.geneontology.io/solr/select?q=%....long text....2Cannotation_class

This happened yesterday as well at first, could be a problem on my side. KEGG is working fine. Anyways, I will just do the GO enrichments on pantherdb.org, so no worries. RNAlysis is otherwise a fantastic tool, thank you!

**Comment by GuyTeichman** [comment]
Hi,
If you want to give it another shot until the new version is released, you could try to exclude both PR and RefSeq from your enrichment analysis. 
I'm not sure about the other error you encountered, but I'll look into it. 

Good luck with your analysis,
Guy.
