### ISSUE TITLE
DESeq2 fails to execute

### ISSUE THREAD

**Issue by dw3015** [GuyTeichman/RNAlysis#21]
* sRNA analysis pipeline version: 3.7.0
* Python version:
* Operating System: MacOS

### Description

Hi there, I am using the stand-alone interface of RNAlysis on MacOS, I have used it with success previously. I am trying to run DESeq2 on the output table generated from kallisto, but it keeps giving me the following error after about 15 seconds of running.

Traceback (most recent call last):
  File "rnalysis/gui/gui.py", line 4130, in finish_generic_job
  File "rnalysis/gui/gui_widgets.py", line 375, in run
  File "rnalysis/filtering.py", line 2864, in differential_expression_deseq2
  File "rnalysis/utils/differential_expression.py", line 130, in run_deseq2_analysis
  File "rnalysis/utils/io.py", line 1416, in run_r_script
AssertionError: R script failed to execute (return code 1). 

Thanks for any help you can provide!

**Comment by GuyTeichman** [comment]
Hi dw3015, 

Could you please copy the text that appears in the RNAlysis log box after you try to run DESeq2?
It should contain a complete report from R/DESeq2 that could help us diagnose the issue further. 

Thanks,
Guy.

**Comment by dw3015** [comment]
Count matrix named 'fed_doubled_kallisto_output_scaled_per_gene.csv'
Attaching package: ‘BiocGenerics’ 
The following objects are masked from ‘package:stats’: 
IQR, mad, sd, var, xtabs 
The following objects are masked from ‘package:base’: 
anyDuplicated, aperm, append, as.data.frame, basename, cbind, 
colnames, dirname, do.call, duplicated, eval, evalq, Filter, Find, 
get, grep, grepl, intersect, is.unsorted, lapply, Map, mapply, 
match, mget, order, paste, pmax, pmax.int, pmin, pmin.int, 
Position, rank, rbind, Reduce, rownames, sapply, setdiff, sort, 
table, tapply, union, unique, unsplit, which.max, which.min 
Attaching package: ‘S4Vectors’ 
The following object is masked from ‘package:utils’: 
findMatches 
The following objects are masked from ‘package:base’: 
expand.grid, I, unname 
Attaching package: ‘MatrixGenerics’ 
The following objects are masked from ‘package:matrixStats’: 
colAlls, colAnyNAs, colAnys, colAvgsPerRowSet, colCollapse, 
colCounts, colCummaxs, colCummins, colCumprods, colCumsums, 
colDiffs, colIQRDiffs, colIQRs, colLogSumExps, colMadDiffs, 
colMads, colMaxs, colMeans2, colMedians, colMins, colOrderStats, 
colProds, colQuantiles, colRanges, colRanks, colSdDiffs, colSds, 
colSums2, colTabulates, colVarDiffs, colVars, colWeightedMads, 
colWeightedMeans, colWeightedMedians, colWeightedSds, 
colWeightedVars, rowAlls, rowAnyNAs, rowAnys, rowAvgsPerColSet, 
rowCollapse, rowCounts, rowCummaxs, rowCummins, rowCumprods, 
rowCumsums, rowDiffs, rowIQRDiffs, rowIQRs, rowLogSumExps, 
rowMadDiffs, rowMads, rowMaxs, rowMeans2, rowMedians, rowMins, 
rowOrderStats, rowProds, rowQuantiles, rowRanges, rowRanks, 
rowSdDiffs, rowSds, rowSums2, rowTabulates, rowVarDiffs, rowVars, 
rowWeightedMads, rowWeightedMeans, rowWeightedMedians, 
rowWeightedSds, rowWeightedVars 
Welcome to Bioconductor 
Vignettes contain introductory material; view with 
'browseVignettes()'. To cite Bioconductor, see 
'citation("Biobase")', and for packages 'citation("pkgname")'. 
Attaching package: ‘Biobase’ 
The following object is masked from ‘package:MatrixGenerics’: 
rowMedians 
The following objects are masked from ‘package:matrixStats’: 
anyMissing, rowMedians 
Loading required package: DESeq2 
Loading required package: S4Vectors 
Loading required package: stats4 
Loading required package: BiocGenerics 
Attaching package: ‘BiocGenerics’ 
The following objects are masked from ‘package:stats’: 
IQR, mad, sd, var, xtabs 
The following objects are masked from ‘package:base’: 
anyDuplicated, aperm, append, as.data.frame, basename, cbind, 
colnames, dirname, do.call, duplicated, eval, evalq, Filter, Find, 
get, grep, grepl, intersect, is.unsorted, lapply, Map, mapply, 
match, mget, order, paste, pmax, pmax.int, pmin, pmin.int, 
Position, rank, rbind, Reduce, rownames, sapply, setdiff, sort, 
table, tapply, union, unique, unsplit, which.max, which.min 
Attaching package: ‘S4Vectors’ 
The following object is masked from ‘package:utils’: 
findMatches 
The following objects are masked from ‘package:base’: 
expand.grid, I, unname 
Loading required package: IRanges 
Loading required package: GenomicRanges 
Loading required package: GenomeInfoDb 
Loading required package: SummarizedExperiment 
Loading required package: MatrixGenerics 
Loading required package: matrixStats 
Attaching package: ‘MatrixGenerics’ 
The following objects are masked from ‘package:matrixStats’: 
colAlls, colAnyNAs, colAnys, colAvgsPerRowSet, colCollapse, 
colCounts, colCummaxs, colCummins, colCumprods, colCumsums, 
colDiffs, colIQRDiffs, colIQRs, colLogSumExps, colMadDiffs, 
colMads, colMaxs, colMeans2, colMedians, colMins, colOrderStats, 
colProds, colQuantiles, colRanges, colRanks, colSdDiffs, colSds, 
colSums2, colTabulates, colVarDiffs, colVars, colWeightedMads, 
colWeightedMeans, colWeightedMedians, colWeightedSds, 
colWeightedVars, rowAlls, rowAnyNAs, rowAnys, rowAvgsPerColSet, 
rowCollapse, rowCounts, rowCummaxs, rowCummins, rowCumprods, 
rowCumsums, rowDiffs, rowIQRDiffs, rowIQRs, rowLogSumExps, 
rowMadDiffs, rowMads, rowMaxs, rowMeans2, rowMedians, rowMins, 
rowOrderStats, rowProds, rowQuantiles, rowRanges, rowRanks, 
rowSdDiffs, rowSds, rowSums2, rowTabulates, rowVarDiffs, rowVars, 
rowWeightedMads, rowWeightedMeans, rowWeightedMedians, 
rowWeightedSds, rowWeightedVars 
Loading required package: Biobase 
Welcome to Bioconductor 
Vignettes contain introductory material; view with 
'browseVignettes()'. To cite Bioconductor, see 
'citation("Biobase")', and for packages 'citation("pkgname")'. 
Attaching package: ‘Biobase’ 
The following object is masked from ‘package:MatrixGenerics’: 
rowMedians 
The following objects are masked from ‘package:matrixStats’: 
anyMissing, rowMedians 
converting counts to integer mode 
Error in `contrasts<-`(`*tmp*`, value = contr.funs[1 + isOF[nn]]) : 
contrasts can be applied only to factors with 2 or more levels 
Calls: DESeqDataSetFromMatrix -> DESeqDataSet -> <Anonymous> -> contrasts<- 
In addition: Warning message: 
In DESeqDataSet(se, design = design, ignoreRank) : 
some variables in design formula are characters, converting to factors 
Execution halted 
Attaching package: ‘BiocGenerics’ 
The following objects are masked from ‘package:stats’: 
IQR, mad, sd, var, xtabs 
The following objects are masked from ‘package:base’: 
anyDuplicated, aperm, append, as.data.frame, basename, cbind, 
colnames, dirname, do.call, duplicated, eval, evalq, Filter, Find, 
get, grep, grepl, intersect, is.unsorted, lapply, Map, mapply, 
match, mget, order, paste, pmax, pmax.int, pmin, pmin.int, 
Position, rank, rbind, Reduce, rownames, sapply, setdiff, sort, 
table, tapply, union, unique, unsplit, which.max, which.min 
Attaching package: ‘S4Vectors’ 
The following object is masked from ‘package:utils’: 
findMatches 
The following objects are masked from ‘package:base’: 
expand.grid, I, unname 
Attaching package: ‘MatrixGenerics’ 
The following objects are masked from ‘package:matrixStats’: 
colAlls, colAnyNAs, colAnys, colAvgsPerRowSet, colCollapse, 
colCounts, colCummaxs, colCummins, colCumprods, colCumsums, 
colDiffs, colIQRDiffs, colIQRs, colLogSumExps, colMadDiffs, 
colMads, colMaxs, colMeans2, colMedians, colMins, colOrderStats, 
colProds, colQuantiles, colRanges, colRanks, colSdDiffs, colSds, 
colSums2, colTabulates, colVarDiffs, colVars, colWeightedMads, 
colWeightedMeans, colWeightedMedians, colWeightedSds, 
colWeightedVars, rowAlls, rowAnyNAs, rowAnys, rowAvgsPerColSet, 
rowCollapse, rowCounts, rowCummaxs, rowCummins, rowCumprods, 
rowCumsums, rowDiffs, rowIQRDiffs, rowIQRs, rowLogSumExps, 
rowMadDiffs, rowMads, rowMaxs, rowMeans2, rowMedians, rowMins, 
rowOrderStats, rowProds, rowQuantiles, rowRanges, rowRanks, 
rowSdDiffs, rowSds, rowSums2, rowTabulates, rowVarDiffs, rowVars, 
rowWeightedMads, rowWeightedMeans, rowWeightedMedians, 
rowWeightedSds, rowWeightedVars 
Welcome to Bioconductor 
Vignettes contain introductory material; view with 
'browseVignettes()'. To cite Bioconductor, see 
'citation("Biobase")', and for packages 'citation("pkgname")'. 
Attaching package: ‘Biobase’ 
The following object is masked from ‘package:MatrixGenerics’: 
rowMedians 
The following objects are masked from ‘package:matrixStats’: 
anyMissing, rowMedians 
Loading required package: DESeq2 
Loading required package: S4Vectors 
Loading required package: stats4 
Loading required package: BiocGenerics 
Attaching package: ‘BiocGenerics’ 
The following objects are masked from ‘package:stats’: 
IQR, mad, sd, var, xtabs 
The following objects are masked from ‘package:base’: 
anyDuplicated, aperm, append, as.data.frame, basename, cbind, 
colnames, dirname, do.call, duplicated, eval, evalq, Filter, Find, 
get, grep, grepl, intersect, is.unsorted, lapply, Map, mapply, 
match, mget, order, paste, pmax, pmax.int, pmin, pmin.int, 
Position, rank, rbind, Reduce, rownames, sapply, setdiff, sort, 
table, tapply, union, unique, unsplit, which.max, which.min 
Attaching package: ‘S4Vectors’ 
The following object is masked from ‘package:utils’: 
findMatches 
The following objects are masked from ‘package:base’: 
expand.grid, I, unname 
Loading required package: IRanges 
Loading required package: GenomicRanges 
Loading required package: GenomeInfoDb 
Loading required package: SummarizedExperiment 
Loading required package: MatrixGenerics 
Loading required package: matrixStats 
Attaching package: ‘MatrixGenerics’ 
The following objects are masked from ‘package:matrixStats’: 
colAlls, colAnyNAs, colAnys, colAvgsPerRowSet, colCollapse, 
colCounts, colCummaxs, colCummins, colCumprods, colCumsums, 
colDiffs, colIQRDiffs, colIQRs, colLogSumExps, colMadDiffs, 
colMads, colMaxs, colMeans2, colMedians, colMins, colOrderStats, 
colProds, colQuantiles, colRanges, colRanks, colSdDiffs, colSds, 
colSums2, colTabulates, colVarDiffs, colVars, colWeightedMads, 
colWeightedMeans, colWeightedMedians, colWeightedSds, 
colWeightedVars, rowAlls, rowAnyNAs, rowAnys, rowAvgsPerColSet, 
rowCollapse, rowCounts, rowCummaxs, rowCummins, rowCumprods, 
rowCumsums, rowDiffs, rowIQRDiffs, rowIQRs, rowLogSumExps, 
rowMadDiffs, rowMads, rowMaxs, rowMeans2, rowMedians, rowMins, 
rowOrderStats, rowProds, rowQuantiles, rowRanges, rowRanks, 
rowSdDiffs, rowSds, rowSums2, rowTabulates, rowVarDiffs, rowVars, 
rowWeightedMads, rowWeightedMeans, rowWeightedMedians, 
rowWeightedSds, rowWeightedVars 
Loading required package: Biobase 
Welcome to Bioconductor 
Vignettes contain introductory material; view with 
'browseVignettes()'. To cite Bioconductor, see 
'citation("Biobase")', and for packages 'citation("pkgname")'. 
Attaching package: ‘Biobase’ 
The following object is masked from ‘package:MatrixGenerics’: 
rowMedians 
The following objects are masked from ‘package:matrixStats’: 
anyMissing, rowMedians 
converting counts to integer mode 
Error in `contrasts<-`(`*tmp*`, value = contr.funs[1 + isOF[nn]]) : 
contrasts can be applied only to factors with 2 or more levels 
Calls: DESeqDataSetFromMatrix -> DESeqDataSet -> <Anonymous> -> contrasts<- 
In addition: Warning message: 
In DESeqDataSet(se, design = design, ignoreRank) : 
some variables in design formula are characters, converting to factors 
Execution halted

**Comment by dw3015** [comment]
I believe I solved it. One group of samples only had a single replicate, and i believe the lack of variance in that group resulted in my error. I was able to pass through the error by removing that group.

**Comment by GuyTeichman** [comment]
That's good to hear! That's my conclusion as well from reading the DESeq2 log. 
In the next version of RNAlysis this issue should give out a clearer indication of what went wrong. 

Best,
Guy.
