### ISSUE TITLE
Needed guidance in installing bowtie2 

### ISSUE THREAD

**Issue by Rajeshwarira** [GuyTeichman/RNAlysis#22]
Hii Guy,
I'm trying to install bowtie2 on my windows. I followed the bowtie2 manual to install it through MinGW. I installed make too. But now I'm stuck here since I don't know to compile bowtie2 tools using makefile. Can you please help me with this.
How can I get it installed to use along with RNAlysis? 
And also can I use Rbowtie2 package in RNAlysis. Is that possible?
Looking forward to hearing from you as soon as possible.
Thank you.
Regards

**Comment by GuyTeichman** [comment]
Hi Rajeshwarira,
To install bowtie2 on Windows, download it using the following link:
https://sourceforge.net/projects/bowtie-bio/files/bowtie2/2.5.1/bowtie2-2.5.1-mingw-x86_64.zip/download
And unzip the directory. 
You don't need to compile bowtie2 at any point. 

Next, make sure you have Perl installed. You can download it from this link:
https://strawberryperl.com/

Once you followed these steps, you should be able to use bowtie2 through RNAlysis. 

Currently, Rbowtie2 is not supported by RNAlysis.

Best, 
Guy.

**Comment by Rajeshwarira** [comment]
Thank you for your response😊

**Comment by Rajeshwarira** [comment]
Hello Guy, 
       I have followed your instructions to install bowtie2 but still I'm not able to use it in RNAlysis.
I'm getting the error mentioned below :

Traceback (most recent call last):

  File "rnalysis\utils\io.py", line 1479, in generate_base_call

  File "rnalysis\utils\io.py", line 1420, in run_subprocess

  File "subprocess.py", line 858, in __init__

  File "subprocess.py", line 1311, in _execute_child

FileNotFoundError: [WinError 2] The system cannot find the file specified

 

During handling of the above exception, another exception occurred:

 

Traceback (most recent call last):

  File "rnalysis\gui\gui.py", line 3697, in finish_generic_job

  File "rnalysis\gui\gui_widgets.py", line 329, in run

  File "rnalysis\fastq.py", line 747, in bowtie2_align_paired_end

  File "rnalysis\fastq.py", line 803, in _parse_bowtie2_misc_args

  File "rnalysis\utils\io.py", line 1482, in generate_base_call

FileNotFoundError: RNAlysis could not find 'bowtie2'. Please ensure that your installation folder is correct, or add it to PATH.

I have been trying to figure out this from the past two days. Still I didn't find any solution.

Can you please help me with this?

Thank you
Regards
