### ISSUE TITLE
pyarrow.vendored.version - closing tabs or saving session

### ISSUE THREAD

**Issue by PaversAssist** [GuyTeichman/RNAlysis#28]
Hello,

I am using RNAlysis for the first time and am able to generate tables, plots etc. However when I go to save my session or close down some tabs/tables I keep getting errors. "ModuleNotFoundError: No module named 'pyarrow.vendored.version'"

I am not experienced generally with coding or python, I have installed pyarrow as well as pandas, but I'm not sure how to get rid of this module error, any help is appreciated.

Thank you
<img width="408" alt="Screenshot 2023-06-22 at 19 48 18" src="https://github.com/GuyTeichman/RNAlysis/assets/137449740/a20899e0-68ed-48be-9449-68ddf02606f0">

**Comment by GuyTeichman** [comment]
Hi PaverAssist,
Thank you for reporting this issue! It should be resolved in RNAlysis version 3.9.2, which will be available to download in ~30 minutes or so. Please try using it and let me know if you keep running into this issue. 

Best,
Guy.

**Comment by PaversAssist** [comment]
Hi Guy,

Just installed the new version and it is working great.

Thanks for the quick fix!
