### ISSUE TITLE
Bug Report: AssertionError: R script failed to execute (return code 1) 

### ISSUE THREAD

**Issue by Mitchzw** [GuyTeichman/RNAlysis#32]
### Describe the bug

Hey
I'm using RNAlysis for the first time. So please bear with me if my problem is stupid :)

I wanted to use DESeq2 differential expression on different datasets but I always get this error report:

Traceback (most recent call last):
  File "rnalysis/gui/gui.py", line 3656, in finish_generic_job
  File "rnalysis/gui/gui_widgets.py", line 291, in run
  File "rnalysis/filtering.py", line 2747, in differential_expression_deseq2
  File "rnalysis/utils/differential_expression.py", line 130, in run_deseq2_analysis
  File "rnalysis/utils/io.py", line 1377, in run_r_script
AssertionError: R script failed to execute (return code 1). 

I installed R and DESeq2. Is it a version problem? I'm using RNAlysis 3.6.0
I tried to install the most recent version but it won't start in contrast to 3.6.0.
I'm using macOS Monterey (12.7) on a MacBook Pro, 2019.

Thanks for any help and all the best
Michael

### Steps To Reproduce

table "elegans_developmental_stages_filt50.0reads_filt50.0reads loaded

General

Run DESeq2 differential expression setup

design matrix loaded

r installation auto

output folder: disable input? checked

comparison Adult vs Embryo

### How did you install RNAlysis?

Stand-alone app

### RNAlysis version

3.6.0

### Operating system

MacOS 12.7

**Comment by GuyTeichman** [comment]
Hi!
Could you please copy and paste here the full error report? That would help me diagnose the problem you ran into. 

Best,
Guy.

**Comment by GuyTeichman** [comment]
OK, seems like it's an issue either with your design table or your count table ("all variables in design formula must be columns in colData"). 
Could you please upload both so I could have a look?

Best,
Guy.

**Comment by Mitchzw** [comment]
Here is the Design Matrix:
[DesignMatrix_Celegans.csv](https://github.com/GuyTeichman/RNAlysis/files/13832152/DesignMatrix_Celegans.csv)

I can't upload the count table. (too big?) 
Instead, here is a screenshot:
<img width="881" alt="Screen Shot 2024-01-04 at 4 40 38 PM" src="https://github.com/GuyTeichman/RNAlysis/assets/54001109/e086f73d-4383-4eab-b1b3-fdc0a9acbd12">

**Comment by GuyTeichman** [comment]
Hi Michael,
The problem appears to be with the design matrix you built. 
Briefly, there are two issues preventing you from running DESeq2 on this dataset:
1. You have included a factor in your design matrix that only has a single value ("Batch" - the samples are all batch "A"). Since there is only a single level for this factor, you can't use it as an explaining factor of variance in your dataset. 
2. The design matrix has the same number of samples and coefficients to fit. In other words - you only have a single sample from each condition. Therefore, DESeq2 cannot estimate the variance of the samples within each condition. 

Tthe dataset you are working with is not composed of individual samples, but is actually an average of many different samples for each condition (dozens to hundreds per condition). 
If you take a look at the full table on wormbase, you can actually find all of the statistics for these datasets - the number of datasets, mean, and standard deviation for each gene in each developmental stage. 
So if you wanted to compare the expression levels of different genes between different developmental stages, you could actually take these statistics and plug them into a simple t-test, since you have all the information you need - mean, STD, and n. 

Unfortunately this is not something RNAlysis can do at the moment, but any statistical program should be able to help you there. 

If you have any more questions or run into more issues, feel free to post again!

Best of luck with your analysis,
Guy.

**Comment by Mitchzw** [comment]
Hey,

thanks a ton for your help!

But now I used another dataset where I have the different experiments separately, also in the design matrix. And I still get the same error message. (still DEseq2)

Design Matrix attached
[DesignMatrix.csv](https://github.com/GuyTeichman/RNAlysis/files/13840344/DesignMatrix.csv)

Screenshot of the data table:
<img width="1572" alt="Screen Shot 2024-01-05 at 10 36 59 AM" src="https://github.com/GuyTeichman/RNAlysis/assets/54001109/fb8c7703-4ccd-4f36-9543-9b008a89ac92">

Error message:
Traceback (most recent call last):
  File "rnalysis/gui/gui.py", line 3656, in finish_generic_job
  File "rnalysis/gui/gui_widgets.py", line 291, in run
  File "rnalysis/filtering.py", line 2747, in differential_expression_deseq2
  File "rnalysis/utils/differential_expression.py", line 130, in run_deseq2_analysis
  File "rnalysis/utils/io.py", line 1377, in run_r_script
AssertionError: R script failed to execute (return code 1). 

What's my mistake here?

**Comment by Mitchzw** [comment]
Here the log:

Count matrix named 'kallisto_output_scaled_per_gene 2_V02.tsv'
Filtered 21331 features, leaving 18215 of the original 39546 features. Filtered inplace.
Warning: This function is meant for raw, unnormalize counts, and your count matrix appears to be normalized. 
Attaching package: ‘BiocGenerics’ 
The following objects are masked from ‘package:stats’: 
IQR, mad, sd, var, xtabs 
The following objects are masked from ‘package:base’: 
anyDuplicated, aperm, append, as.data.frame, basename, cbind, 
colnames, dirname, do.call, duplicated, eval, evalq, Filter, Find, 
get, grep, grepl, intersect, is.unsorted, lapply, Map, mapply, 
match, mget, order, paste, pmax, pmax.int, pmin, pmin.int, 
Position, rank, rbind, Reduce, rownames, sapply, setdiff, sort, 
table, tapply, union, unique, unsplit, which.max, which.min 
Attaching package: ‘S4Vectors’ 
The following object is masked from ‘package:utils’: 
findMatches 
The following objects are masked from ‘package:base’: 
expand.grid, I, unname 
Attaching package: ‘MatrixGenerics’ 
The following objects are masked from ‘package:matrixStats’: 
colAlls, colAnyNAs, colAnys, colAvgsPerRowSet, colCollapse, 
colCounts, colCummaxs, colCummins, colCumprods, colCumsums, 
colDiffs, colIQRDiffs, colIQRs, colLogSumExps, colMadDiffs, 
colMads, colMaxs, colMeans2, colMedians, colMins, colOrderStats, 
colProds, colQuantiles, colRanges, colRanks, colSdDiffs, colSds, 
colSums2, colTabulates, colVarDiffs, colVars, colWeightedMads, 
colWeightedMeans, colWeightedMedians, colWeightedSds, 
colWeightedVars, rowAlls, rowAnyNAs, rowAnys, rowAvgsPerColSet, 
rowCollapse, rowCounts, rowCummaxs, rowCummins, rowCumprods, 
rowCumsums, rowDiffs, rowIQRDiffs, rowIQRs, rowLogSumExps, 
rowMadDiffs, rowMads, rowMaxs, rowMeans2, rowMedians, rowMins, 
rowOrderStats, rowProds, rowQuantiles, rowRanges, rowRanks, 
rowSdDiffs, rowSds, rowSums2, rowTabulates, rowVarDiffs, rowVars, 
rowWeightedMads, rowWeightedMeans, rowWeightedMedians, 
rowWeightedSds, rowWeightedVars 
Welcome to Bioconductor 
Vignettes contain introductory material; view with 
'browseVignettes()'. To cite Bioconductor, see 
'citation("Biobase")', and for packages 'citation("pkgname")'. 
Attaching package: ‘Biobase’ 
The following object is masked from ‘package:MatrixGenerics’: 
rowMedians 
The following objects are masked from ‘package:matrixStats’: 
anyMissing, rowMedians 
Loading required package: DESeq2 
Loading required package: S4Vectors 
Loading required package: stats4 
Loading required package: BiocGenerics 
Attaching package: ‘BiocGenerics’ 
The following objects are masked from ‘package:stats’: 
IQR, mad, sd, var, xtabs 
The following objects are masked from ‘package:base’: 
anyDuplicated, aperm, append, as.data.frame, basename, cbind, 
colnames, dirname, do.call, duplicated, eval, evalq, Filter, Find, 
get, grep, grepl, intersect, is.unsorted, lapply, Map, mapply, 
match, mget, order, paste, pmax, pmax.int, pmin, pmin.int, 
Position, rank, rbind, Reduce, rownames, sapply, setdiff, sort, 
table, tapply, union, unique, unsplit, which.max, which.min 
Attaching package: ‘S4Vectors’ 
The following object is masked from ‘package:utils’: 
findMatches 
The following objects are masked from ‘package:base’: 
expand.grid, I, unname 
Loading required package: IRanges 
Loading required package: GenomicRanges 
Loading required package: GenomeInfoDb 
Loading required package: SummarizedExperiment 
Loading required package: MatrixGenerics 
Loading required package: matrixStats 
Attaching package: ‘MatrixGenerics’ 
The following objects are masked from ‘package:matrixStats’: 
colAlls, colAnyNAs, colAnys, colAvgsPerRowSet, colCollapse, 
colCounts, colCummaxs, colCummins, colCumprods, colCumsums, 
colDiffs, colIQRDiffs, colIQRs, colLogSumExps, colMadDiffs, 
colMads, colMaxs, colMeans2, colMedians, colMins, colOrderStats, 
colProds, colQuantiles, colRanges, colRanks, colSdDiffs, colSds, 
colSums2, colTabulates, colVarDiffs, colVars, colWeightedMads, 
colWeightedMeans, colWeightedMedians, colWeightedSds, 
colWeightedVars, rowAlls, rowAnyNAs, rowAnys, rowAvgsPerColSet, 
rowCollapse, rowCounts, rowCummaxs, rowCummins, rowCumprods, 
rowCumsums, rowDiffs, rowIQRDiffs, rowIQRs, rowLogSumExps, 
rowMadDiffs, rowMads, rowMaxs, rowMeans2, rowMedians, rowMins, 
rowOrderStats, rowProds, rowQuantiles, rowRanges, rowRanks, 
rowSdDiffs, rowSds, rowSums2, rowTabulates, rowVarDiffs, rowVars, 
rowWeightedMads, rowWeightedMeans, rowWeightedMedians, 
rowWeightedSds, rowWeightedVars 
Loading required package: Biobase 
Welcome to Bioconductor 
Vignettes contain introductory material; view with 
'browseVignettes()'. To cite Bioconductor, see 
'citation("Biobase")', and for packages 'citation("pkgname")'. 
Attaching package: ‘Biobase’ 
The following object is masked from ‘package:MatrixGenerics’: 
rowMedians 
The following objects are masked from ‘package:matrixStats’: 
anyMissing, rowMedians 
converting counts to integer mode 
Error in DESeqDataSet(se, design = design, ignoreRank) : 
all variables in design formula must be columns in colData 
Calls: DESeqDataSetFromMatrix -> DESeqDataSet 
Execution halted

**Comment by GuyTeichman** [comment]
Hi,
Could you please upload the first 5 rows of your counts table?
You can do that through RNAlysis by using the "table head" function under the "Summarize" category:
![image](https://github.com/GuyTeichman/RNAlysis/assets/48219633/c5490a99-1a1e-4504-ae33-072e3f91c4ea)
Then save the table as CSV and upload it here.

**Comment by Mitchzw** [comment]
Hey,

here are the top 20:
[head.csv](https://github.com/GuyTeichman/RNAlysis/files/13843073/head.csv)

I simplified the names of the experiments compared to what I uploaded before. So here is also the updated design matrix. But the result and error message is exactly the same.

[DesignMatrix_V02.csv](https://github.com/GuyTeichman/RNAlysis/files/13843104/DesignMatrix_V02.csv)

**Comment by GuyTeichman** [comment]
Hi,
I think I might have managed to figure out the issue. Can you try running differential expression analysis on your full counts table using this edited design matrix?
[DesignMatrix_V03.csv](https://github.com/GuyTeichman/RNAlysis/files/13843690/DesignMatrix_V03.csv)

**Comment by Mitchzw** [comment]
Awesome, now it worked!

So the problems were the additional (empty) columns in my initial file, I saw?

**Comment by GuyTeichman** [comment]
Yes, it appears that this was the problem. 

Good luck with your analysis!
Guy
