### ISSUE TITLE
Bug Report: Unable to import RNAlysis into python

### ISSUE THREAD

**Issue by Celine-075** [GuyTeichman/RNAlysis#35]
### Describe the bug

Hi, 

I am using Windows 11, Spyder IDE 5.4.3 and Python 3.11.5. 

I installed RNAlysis through `pip install RNAlysis[all]`. 

However, when I try to import the package with 'from rnalysis import fastq`, I get the following error code:

Traceback (most recent call last):

  Cell In[12], line 1
    from rnalysis import fastq

  File ~\anaconda3\Lib\site-packages\rnalysis\fastq.py:21
    from rnalysis import filtering

  File ~\anaconda3\Lib\site-packages\rnalysis\filtering.py:37
    class Filter:

  File ~\anaconda3\Lib\site-packages\rnalysis\filtering.py:452 in Filter
    def find_paralogs_ensembl(self, organism: Union[Literal['auto'], str, int, Literal[get_ensembl_taxons()]] = 'auto',

  File ~\anaconda3\Lib\site-packages\rnalysis\utils\param_typing.py:118 in get_ensembl_taxons
    taxons = parsing.data_to_tuple(io.get_legal_ensembl_taxons())

  File ~\anaconda3\Lib\site-packages\rnalysis\utils\io.py:2116 in get_legal_ensembl_taxons
    results = client.run()[0]['species']

  File ~\anaconda3\Lib\site-packages\rnalysis\utils\io.py:1115 in run
    res = asyncio.run(self._run())

  File ~\anaconda3\Lib\asyncio\runners.py:186 in run
    raise RuntimeError(

RuntimeError: asyncio.run() cannot be called from a running event loop

Now when I check asyncio with `pip show asyncio`, it does say that I have it: 

Name: asyncio
Version: 3.4.3
Summary: reference implementation of PEP 3156
Home-page: http://www.python.org/dev/peps/pep-3156/
Author: UNKNOWN
Author-email: UNKNOWN
License: UNKNOWN
Location: C:\Users\Celin\anaconda3\Lib\site-packages
Requires: 
Required-by: 
Note: you may need to restart the kernel to use updated packages.

It also said I needed GraphViz and add it to PATH, but I did that. 

**Can you help me solve this problem?** 

Kind Regards, 

Celine 

### Steps To Reproduce

1. install RNAlysis through `pip install RNAlysis[all]`. 
2. import package with 'from rnalysis import fastq`

### Expected behavior

I expected to just import the package and being able to use it. 

### Screenshots

![error rnalysis](https://github.com/GuyTeichman/RNAlysis/assets/127406679/9b7c0faf-3942-4cc2-b42c-3e3e1271e0a8)

### How did you install RNAlysis?

installed via pip/Python

### RNAlysis version

3.11.0

### Operating system

Windows 11

**Comment by GuyTeichman** [comment]
Hi Celine! Thank you for reporting this issue.
It appears that the Spyder IDE doesn't play nice with packages that depend on "asyncio" (such as RNAlysis).
I'm hoping to release an update in a week or two that will address this issue.

Until then, I can offer two workarounds:
1. Use a different IDE, such as Pycharm Community Edition
2. Install the python package `nest-asyncio`, and run the following code snippet to import rnalysis:
`import nest_asyncio
nest_asyncio.apply()
from RNAlysis import fastq
`
I'm not 100% sure if the second one will work for you, do please let me know if that solved the problem for you.

Best,
Guy.

**Comment by Celine-075** [comment]
Option 2 does not work for me. When I follow your instructions I get the following error: 
![error_rnalysis2](https://github.com/GuyTeichman/RNAlysis/assets/127406679/17cc63d8-e286-42c8-a559-d810bba09c69)

When I add `import graphviz` (just to be sure), I get this: 
![error_rnalysis3](https://github.com/GuyTeichman/RNAlysis/assets/127406679/b21528e7-1e4c-49d9-8943-28ba61ef38e2)

Im going to try another IDE like Pycharm now. I'll update you.

**Comment by GuyTeichman** [comment]
Interesting - this appears to be a different issue (this time with the CutAdapt package), but also related to Spyder-specific shenanigans. We could try monkeypatching sys.stdout before importing cutadapt (and rnalysis), but this might cause Spyder to work incorrectly (or not work at all). 
Let me know if PyCharm works for you, and in the meantime I'll see if I can figure out a solution for this issue.

Thanks,
Guy.
