### ISSUE TITLE
DeSeq2 Error 

### ISSUE THREAD

**Issue by HannahNeuendorf** [GuyTeichman/RNAlysis#36]
### Describe the bug

I'm attempting to run a DESeq2 differential expression analysis but am getting the following error: 

R script failed to execute: 'Error in contrib.url(repos, "source") : trying to use CRAN without setting a mirror'. See full error report below.

Full error report: 

RuntimeError: See R log below. 
Installing package into 'C:/Users/hanna/AppData/Local/R/win-library/4.3'
(as 'lib' is unspecified)
Error in contrib.url(repos, "source") :
  trying to use CRAN without setting a mirror
Calls: install.packages -> contrib.url
Execution halted

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "rnalysis\gui\gui.py", line 4340, in finish_generic_job

  File "rnalysis\gui\gui_widgets.py", line 382, in run

  File "rnalysis\filtering.py", line 3204, in differential_expression_deseq2

  File "rnalysis\utils\differential_expression.py", line 122, in run_deseq2_analysis

  File "rnalysis\utils\installs.py", line 101, in install_deseq2

  File "rnalysis\utils\io.py", line 2303, in run_r_script

ChildProcessError: R script failed to execute: 'Error in contrib.url(repos, "source") :  trying to use CRAN without setting a mirror'. See full error report below.

Any assistance debugging this would be greatly appreciated, I'm not an R user so struggling to debug this issue. 

 

### Steps To Reproduce

Error appears when clicking 'Start DeSeq2' after inputting all information as described in the tutorial. 

### How did you install RNAlysis?

Stand-alone app

### RNAlysis version

3.11.0

### Operating system

Windows 11

**Comment by GuyTeichman** [comment]
Hi Hannah,
My apologies for the late response, and thank you for raising the issue and pointing out the solution!
On the next release of RNAlysis I will add a CRAN mirror to the automatic DESeq2 installation script so this will no longer be an issue. 

Thanks,
Guy.
