### ISSUE TITLE
Can´t get DEseq2 differential expression anallysis to work :(

### ISSUE THREAD

**Issue by Mintxoklet** [GuyTeichman/RNAlysis#7]
Well I didnt really know where to post my issue since it is probably not a bug. With that being said, I was trying to perform differential expression from my count matrix generated with kallisto (and filtered). However an error pops up that says the following:
Traceback (most recent call last):
  File "C:\Users\Jon\AppData\Local\Programs\Python\Python310\lib\site-packages\rnalysis\gui\gui.py", line 3425, in finish_generic_job
    raise worker_output[0]
  File "C:\Users\Jon\AppData\Local\Programs\Python\Python310\lib\site-packages\rnalysis\gui\gui_widgets.py", line 268, in run
    result = self.partial()
  File "C:\Users\Jon\AppData\Local\Programs\Python\Python310\lib\site-packages\rnalysis\filtering.py", line 2524, in differential_expression_deseq2
    output_dir = differential_expression.run_deseq2_analysis(data_path, design_matrix, comparisons,
  File "C:\Users\Jon\AppData\Local\Programs\Python\Python310\lib\site-packages\rnalysis\utils\differential_expression.py", line 55, in run_deseq2_analysis
    io.run_r_script(script_path, r_installation_folder)
  File "C:\Users\Jon\AppData\Local\Programs\Python\Python310\lib\site-packages\rnalysis\utils\io.py", line 1278, in run_r_script
    assert not return_code, f"R script failed to execute (return code {return_code}). "
AssertionError: R script failed to execute (return code 1). 

I hope maybe you can help me as I have absolutely no clue about how to solve it. Thank you very much and happy new year!

**Comment by GuyTeichman** [comment]
Hi,
It looks like DESeq2 failed for some reason.
The log textbox at the bottom of the screen should contain all of the output from the DESeq2 run, including additional information about the error it encountered.
Could you please copy and paste that report here? That will really help me figure out the problem. 

Thanks and have a great new year!
Guy

**Comment by Mintxoklet** [comment]
Hello, thanks for the quick response!
Here is the log you are looking for, in addition to the error prompt above. By the way, I am feeding the counts matrix without normalization to DEseq2, is this correct?
Welcome to RNAlysis! 
Count matrix named 'Bcell_raw_quantification_filt5.0reads.csv'

Attaching package: 'BiocGenerics' 

The following objects are masked from 'package:stats': 

IQR, mad, sd, var, xtabs 

The following objects are masked from 'package:base': 

anyDuplicated, aperm, append, as.data.frame, basename, cbind, 
colnames, dirname, do.call, duplicated, eval, evalq, Filter, Find, 
get, grep, grepl, intersect, is.unsorted, lapply, Map, mapply, 
match, mget, order, paste, pmax, pmax.int, pmin, pmin.int, 
Position, rank, rbind, Reduce, rownames, sapply, setdiff, sort, 
table, tapply, union, unique, unsplit, which.max, which.min 


Attaching package: 'S4Vectors' 

The following objects are masked from 'package:base': 

expand.grid, I, unname 


Attaching package: 'IRanges' 

The following object is masked from 'package:grDevices': 

windows 


Attaching package: 'MatrixGenerics' 

The following objects are masked from 'package:matrixStats': 

colAlls, colAnyNAs, colAnys, colAvgsPerRowSet, colCollapse, 
colCounts, colCummaxs, colCummins, colCumprods, colCumsums, 
colDiffs, colIQRDiffs, colIQRs, colLogSumExps, colMadDiffs, 
colMads, colMaxs, colMeans2, colMedians, colMins, colOrderStats, 
colProds, colQuantiles, colRanges, colRanks, colSdDiffs, colSds, 
colSums2, colTabulates, colVarDiffs, colVars, colWeightedMads, 
colWeightedMeans, colWeightedMedians, colWeightedSds, 
colWeightedVars, rowAlls, rowAnyNAs, rowAnys, rowAvgsPerColSet, 
rowCollapse, rowCounts, rowCummaxs, rowCummins, rowCumprods, 
rowCumsums, rowDiffs, rowIQRDiffs, rowIQRs, rowLogSumExps, 
rowMadDiffs, rowMads, rowMaxs, rowMeans2, rowMedians, rowMins, 
rowOrderStats, rowProds, rowQuantiles, rowRanges, rowRanks, 
rowSdDiffs, rowSds, rowSums2, rowTabulates, rowVarDiffs, rowVars, 
rowWeightedMads, rowWeightedMeans, rowWeightedMedians, 
rowWeightedSds, rowWeightedVars 

Welcome to Bioconductor 

Vignettes contain introductory material; view with 
'browseVignettes()'. To cite Bioconductor, see 
'citation("Biobase")', and for packages 'citation("pkgname")'. 


Attaching package: 'Biobase' 

The following object is masked from 'package:MatrixGenerics': 

rowMedians 

The following objects are masked from 'package:matrixStats': 

anyMissing, rowMedians 

Loading required package: DESeq2 
Loading required package: S4Vectors 
Loading required package: stats4 
Loading required package: BiocGenerics 

Attaching package: 'BiocGenerics' 

The following objects are masked from 'package:stats': 

IQR, mad, sd, var, xtabs 

The following objects are masked from 'package:base': 

anyDuplicated, aperm, append, as.data.frame, basename, cbind, 
colnames, dirname, do.call, duplicated, eval, evalq, Filter, Find, 
get, grep, grepl, intersect, is.unsorted, lapply, Map, mapply, 
match, mget, order, paste, pmax, pmax.int, pmin, pmin.int, 
Position, rank, rbind, Reduce, rownames, sapply, setdiff, sort, 
table, tapply, union, unique, unsplit, which.max, which.min 


Attaching package: 'S4Vectors' 

The following objects are masked from 'package:base': 

expand.grid, I, unname 

Loading required package: IRanges 

Attaching package: 'IRanges' 

The following object is masked from 'package:grDevices': 

windows 

Loading required package: GenomicRanges 
Loading required package: GenomeInfoDb 
Loading required package: SummarizedExperiment 
Loading required package: MatrixGenerics 
Loading required package: matrixStats 

Attaching package: 'MatrixGenerics' 

The following objects are masked from 'package:matrixStats': 

colAlls, colAnyNAs, colAnys, colAvgsPerRowSet, colCollapse, 
colCounts, colCummaxs, colCummins, colCumprods, colCumsums, 
colDiffs, colIQRDiffs, colIQRs, colLogSumExps, colMadDiffs, 
colMads, colMaxs, colMeans2, colMedians, colMins, colOrderStats, 
colProds, colQuantiles, colRanges, colRanks, colSdDiffs, colSds, 
colSums2, colTabulates, colVarDiffs, colVars, colWeightedMads, 
colWeightedMeans, colWeightedMedians, colWeightedSds, 
colWeightedVars, rowAlls, rowAnyNAs, rowAnys, rowAvgsPerColSet, 
rowCollapse, rowCounts, rowCummaxs, rowCummins, rowCumprods, 
rowCumsums, rowDiffs, rowIQRDiffs, rowIQRs, rowLogSumExps, 
rowMadDiffs, rowMads, rowMaxs, rowMeans2, rowMedians, rowMins, 
rowOrderStats, rowProds, rowQuantiles, rowRanges, rowRanks, 
rowSdDiffs, rowSds, rowSums2, rowTabulates, rowVarDiffs, rowVars, 
rowWeightedMads, rowWeightedMeans, rowWeightedMedians, 
rowWeightedSds, rowWeightedVars 

Loading required package: Biobase 
Welcome to Bioconductor 

Vignettes contain introductory material; view with 
'browseVignettes()'. To cite Bioconductor, see 
'citation("Biobase")', and for packages 'citation("pkgname")'. 


Attaching package: 'Biobase' 

The following object is masked from 'package:MatrixGenerics': 

rowMedians 

The following objects are masked from 'package:matrixStats': 

anyMissing, rowMedians 

converting counts to integer mode 
Error in DESeqDataSet(se, design = design, ignoreRank) : 
all variables in design formula must be columns in colData 
Calls: DESeqDataSetFromMatrix -> DESeqDataSet 
Ejecución interrumpida

**Comment by Mintxoklet** [comment]
Hello again, 
So even with my astonishing lack of informatics knowledge I managed to solve the error, seems like it. Some time ago I was trying to use another program which required a .csv file. Creating a .csv file is straightforward, however, the program didn't seem to work with the .csv I was providing. Intrigued, when I analyzed the csv in a notepad (as i usually open them with excel) I realized that the field separator was actually a semicolon ; instead of a regular comma,. Happens that in Europe, as comma is used for decimal places frequently, and apps such as excel use the semicolon as separator by default to avoid problems. 
Just for the sake of trying I replaced the semicolons with commas in my design matrix and DEseq2 has run without errors!
I hope this can help if it ever happens to someone else. Cheers! (for now LOL). Great software for programming noobs like me by the way!

**Comment by GuyTeichman** [comment]
I'm glad to hear you figured out the problem!
I had another look at the code, and it seems like you did find a bug - _RNAlysis_ can detect the delimiter in your design matrix file automatically, but when it sends the design matrix to DESeq2 it assumes that the delimiter is always a comma. 
I'm writing a fix, which should be released in the next _RNAlysis_ version. 

Thank you, and good luck with your analysis!
